spring.datasource.url=jdbc:postgresql://localhost:5432/sistemadecadastro
spring.datasource.username=postgres
spring.datasource.password=java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true